name: Deploy ptas.de

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/ptas/**
      - packages/**
      - package.json
      - bun.lock
      - bunfig.toml
      - turbo.json
      - tsconfig.base.json
      - .github/workflows/deploy-ptas.yml
      - .github/workflows/azure-static-web-app.yml
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main
    paths:
      - apps/ptas/**
      - packages/**
      - package.json
      - bun.lock
      - bunfig.toml
      - turbo.json
      - tsconfig.base.json
      - .github/workflows/deploy-ptas.yml
      - .github/workflows/azure-static-web-app.yml

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    uses: ./.github/workflows/azure-static-web-app.yml
    with:
      app: ptas
    secrets:
      azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_WAVE_039B6B203 }}
